spring:
  application:
    name: item-service
  rabbitmq:
    host: 176.198.106.214
    port: 5672
    username: admin
    password: admin    
#server:
#  port: 8001

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka    #先eureka连接服务器器
---
 spring:
  profiles: item1
  
 server:
  port: 8001
---
spring:
  profiles: item2

server:
  port: 8002     